[versions]
activity = "1.12.1"
agp = "8.13.2"
biometric = "1.2.0-alpha05"
coil = "2.7.0"
commons-compress = "1.28.0"
commons-io = "2.21.0"
compose-bom = "2025.10.00"
compose = "1.10.0"
compose-accompanist = "0.37.3"
compose-markdown = "0.5.7"
coroutines = "1.10.2"
datastore = "1.2.0"
documentfile = "1.1.0"
immutables = "0.4.0"
junit-jupiter = "6.0.1"
kaml = "0.104.0"
koin = "4.1.1"
koin-ksp = "2.3.1"
kotlin = "2.3.0"
ksp = "2.3.2"
libsu = "6.0.0"
lifecycle = "2.10.0"
material = "1.13.0"
navigation = "2.9.6"
navigation3 = "1.0.0"
# TODO migrate to 2.0.X when ready https://pgpainless.readthedocs.io/en/latest/pgpainless-core/migration_2.0.html
pgpainless = "1.7.7"
preference = "1.2.1"
room = "2.8.4"
security = "1.1.0"
semver = "4.3.0"
serialization = "1.9.0"
test = "1.7.0"
test-rules = "1.7.0"
test-ext = "1.3.0"
timber = "5.0.1"
work = "2.11.0"
zstd-jni = "1.5.7-6"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutables" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
material = { module = "com.google.android.material:material", version.ref = "material" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }

libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
libsu-io = { module = "com.github.topjohnwu.libsu:io", version.ref = "libsu" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
security-crypto = { module = "androidx.security:security-crypto-ktx", version.ref = "security" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd-jni" }
pgpainless = { module = "org.pgpainless:pgpainless-core", version.ref = "pgpainless" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
semver = { module = "de.voize:semver4k", version.ref = "semver" }
kotlin-main-kts = { module = "org.jetbrains.kotlin:kotlin-main-kts", version.ref = "kotlin" }

lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-navigationsuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-navigation3 = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
compose-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "compose-accompanist" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "compose-markdown" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

test-runner = { module = "androidx.test:runner", version.ref = "test" }
test-rules = { module = "androidx.test:rules", version.ref = "test-rules" }
test-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "test-ext" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-scripting = { id = "org.jetbrains.kotlin.plugin.scripting", version.ref = "kotlin" }
